run:
  timeout: 5m
  issues-exit-code: 1
  modules-download-mode: readonly
  skip-dirs:
    - ./grpc

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  govet:
    check-shadowing: true

linters:
  enable:
    - deadcode
    - errcheck
    - megacheck # (staticcheck + gosimple + unused in one linter)
    - govet
    - ineffassign
    - structcheck
    - varcheck

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
